# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  pathcasemvc:
    image: pathcasemvc
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    environment: 
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - mongo
      - pathcaseidentity
      - redis
  pathcaseidentity:
    image: pathcaseidentity
    build:
      context: ./PathCase.IdentityServer
      dockerfile: ./Dockerfile
    expose: 
      - 5001
    ports:
      - 5001:5001
    environment: 
      - ASPNETCORE_ENVIRONMENT="Development"
      - ASPNETCORE_URLS=http://+:5001
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  redis:
    image: redis
    ports:
      - 6379:6379